// 복통 온톨로지 — YAML→Cypher 자동생성. 정본=ontology/abdominal_pain.yaml. 손편집 금지.
MATCH (n) DETACH DELETE n;
MERGE (:ChiefComplaint {id:"abdominal_pain", label:"복통"});
MERGE (:DiseasePrimary {id:"acute_appendicitis", label:"급성 충수염"});
MERGE (:Symptom {id:"rlq_pain", label:"우하복부 통증"});
MERGE (:Symptom {id:"pain_migration_periumbilical_to_rlq", label:"배꼽 주위→우하복부 통증 이동"});
MERGE (:Symptom {id:"fever_low_grade", label:"미열"});
MERGE (:Symptom {id:"anorexia", label:"식욕부진"});
MERGE (:Symptom {id:"nausea_vomiting", label:"오심/구토"});
MERGE (:Symptom {id:"rebound_tenderness", label:"반발통"});
MERGE (:RedFlag {id:"peritoneal_sign", label:"복막자극징후"});
MERGE (:RedFlag {id:"high_fever", label:"고열"});
MERGE (:ChecklistItem {id:"ask_onset_duration", label:"발병·기간 묻기"});
MERGE (:ChecklistItem {id:"ask_location_migration", label:"통증 위치·이동 묻기"});
MERGE (:ChecklistItem {id:"ask_associated_fever_gi", label:"발열·소화기 동반증상 묻기"});
MERGE (:ChecklistItem {id:"exam_rebound_tenderness", label:"반발통·압통 진찰"});
MERGE (:Test {id:"abdominal_ct", label:"복부 CT"});
MERGE (:Test {id:"cbc", label:"전혈구검사(CBC)"});
MERGE (:DiseaseDifferential {id:"peptic_ulcer_disease", label:"소화성 궤양"});
MERGE (:Symptom {id:"epigastric_pain", label:"상복부 통증"});
MERGE (:Symptom {id:"relation_to_meals", label:"식사와 연관(공복/식후)"});
MERGE (:Symptom {id:"heartburn", label:"속쓰림"});
MERGE (:Symptom {id:"nocturnal_pain", label:"야간통"});
MERGE (:Symptom {id:"relieved_by_antacid", label:"제산제로 완화"});
MERGE (:Symptom {id:"melena", label:"흑색변"});
MERGE (:Symptom {id:"postprandial_vomiting", label:"식후 구토(협착 시)"});
MERGE (:RedFlag {id:"gi_bleeding", label:"위장관 출혈"});
MERGE (:RedFlag {id:"perforation_sign", label:"천공 징후(판자 같은 배)"});
MERGE (:RedFlag {id:"gastric_cancer_ddx", label:"위암(감별)"});
MERGE (:ChecklistItem {id:"ask_meal_relation", label:"식사 연관 묻기"});
MERGE (:ChecklistItem {id:"ask_heartburn", label:"속쓰림 묻기"});
MERGE (:ChecklistItem {id:"ask_nsaid_history", label:"NSAID 복용력 묻기"});
MERGE (:ChecklistItem {id:"ask_alarm_features", label:"경고증상(출혈·체중감소) 묻기"});
MERGE (:Test {id:"egd", label:"위내시경"});
MERGE (:DiseaseDifferential {id:"acute_cholecystitis", label:"급성 담낭염/담석산통"});
MERGE (:Symptom {id:"ruq_pain", label:"우상복부 통증"});
MERGE (:Symptom {id:"worse_after_fatty_meal", label:"기름진 음식 후 악화"});
MERGE (:Symptom {id:"radiation_to_right_shoulder", label:"우측 어깨로 방사"});
MERGE (:Symptom {id:"murphy_sign", label:"Murphy 징후"});
MERGE (:Symptom {id:"fever_chill", label:"발열/오한"});
MERGE (:Symptom {id:"jaundice", label:"황달"});
MERGE (:RedFlag {id:"charcot_triad", label:"담관염(고열·황달·복통)"});
MERGE (:ChecklistItem {id:"ask_pain_location_radiation", label:"통증 위치·방사 묻기"});
MERGE (:ChecklistItem {id:"ask_food_relation", label:"음식 연관 묻기"});
MERGE (:ChecklistItem {id:"ask_fever_jaundice", label:"발열·황달 묻기"});
MERGE (:ChecklistItem {id:"exam_murphy_sign", label:"Murphy 징후 진찰"});
MERGE (:Test {id:"abdominal_ultrasound", label:"복부 초음파"});
MERGE (:Test {id:"lft", label:"간기능검사"});
MERGE (:DiseaseDifferential {id:"acute_pancreatitis", label:"급성 췌장염"});
MERGE (:Symptom {id:"radiation_to_back", label:"등으로 방사"});
MERGE (:Symptom {id:"worse_lying_better_leaning_forward", label:"누우면 악화·앞으로 숙이면 완화"});
MERGE (:Symptom {id:"persistent_severe_pain", label:"지속적 극심한 통증"});
MERGE (:Symptom {id:"alcohol_or_gallstone_history", label:"음주·담석 과거력"});
MERGE (:RedFlag {id:"shock_organ_failure", label:"쇼크·장기부전"});
MERGE (:ChecklistItem {id:"ask_alcohol_history", label:"음주력 묻기"});
MERGE (:ChecklistItem {id:"ask_nausea_vomiting", label:"오심·구토 묻기"});
MERGE (:ChecklistItem {id:"ask_prior_gallstone", label:"담석 병력 묻기"});
MERGE (:Test {id:"serum_lipase_amylase", label:"혈청 리파아제/아밀라아제"});
MERGE (:DiseaseDifferential {id:"gastroenteritis", label:"위장관염"});
MERGE (:Symptom {id:"diffuse_crampy_pain", label:"광범위 쥐어짜는 복통"});
MERGE (:Symptom {id:"diarrhea", label:"설사"});
MERGE (:Symptom {id:"recent_food_or_contact", label:"최근 음식·접촉력"});
MERGE (:Symptom {id:"mild_self_limiting", label:"경증·자연호전 경향"});
MERGE (:RedFlag {id:"dehydration_sign", label:"탈수 징후"});
MERGE (:RedFlag {id:"bloody_stool", label:"혈변"});
MERGE (:ChecklistItem {id:"ask_diarrhea", label:"설사 묻기"});
MERGE (:ChecklistItem {id:"ask_food_history", label:"음식력 묻기"});
MERGE (:ChecklistItem {id:"ask_sick_contacts", label:"유사증상 접촉 묻기"});
MERGE (:ChecklistItem {id:"ask_dehydration", label:"탈수증상 묻기"});
MERGE (:Test {id:"stool_test", label:"대변검사"});
MERGE (:DiseaseDifferential {id:"bowel_obstruction", label:"장폐색"});
MERGE (:Symptom {id:"crampy_abdominal_pain", label:"쥐어짜는 복통(간헐)"});
MERGE (:Symptom {id:"abdominal_distension", label:"복부 팽만"});
MERGE (:Symptom {id:"vomiting", label:"구토"});
MERGE (:Symptom {id:"obstipation", label:"배변·가스 중단"});
MERGE (:Symptom {id:"hyperactive_then_absent_bowel_sounds", label:"항진→소실 장음"});
MERGE (:RedFlag {id:"strangulation_sign", label:"교액(strangulation) 징후"});
MERGE (:ChecklistItem {id:"ask_bowel_gas_passage", label:"배변·가스 배출 묻기"});
MERGE (:ChecklistItem {id:"ask_prior_surgery", label:"수술력 묻기"});
MERGE (:ChecklistItem {id:"ask_vomiting", label:"구토 묻기"});
MERGE (:ChecklistItem {id:"exam_abdominal_distension", label:"복부 팽만 진찰"});
MERGE (:Test {id:"abdominal_xray", label:"복부 단순촬영"});
MERGE (:DiseaseDifferential {id:"diverticulitis", label:"게실염"});
MERGE (:Symptom {id:"llq_pain", label:"좌하복부 통증"});
MERGE (:Symptom {id:"fever", label:"발열"});
MERGE (:Symptom {id:"altered_bowel_habit", label:"배변습관 변화"});
MERGE (:Symptom {id:"localized_tenderness", label:"국소 압통"});
MERGE (:ChecklistItem {id:"ask_pain_location", label:"통증 위치 묻기"});
MERGE (:ChecklistItem {id:"ask_bowel_habit_change", label:"배변습관 변화 묻기"});
MERGE (:ChecklistItem {id:"ask_fever", label:"발열 묻기"});
MERGE (:ChecklistItem {id:"exam_llq_tenderness", label:"좌하복부 압통 진찰"});
MERGE (:DiseaseDifferential {id:"ureteral_stone", label:"요관결석"});
MERGE (:Symptom {id:"flank_pain", label:"옆구리 통증"});
MERGE (:Symptom {id:"sudden_severe_pain", label:"갑작스런 극심한 통증"});
MERGE (:Symptom {id:"cva_tenderness", label:"갈비척추각압통(CVA tenderness)"});
MERGE (:Symptom {id:"position_independent_pain", label:"자세 무관 지속통증"});
MERGE (:Symptom {id:"hematuria", label:"혈뇨"});
MERGE (:Symptom {id:"radiation_to_groin", label:"서혜부로 방사"});
MERGE (:RedFlag {id:"obstruction_pyelonephritis", label:"폐색성 신우신염(합병증)"});
MERGE (:RedFlag {id:"acute_kidney_injury", label:"급성 신부전(합병증)"});
MERGE (:ChecklistItem {id:"ask_character", label:"통증 양상 묻기"});
MERGE (:ChecklistItem {id:"ask_fever_chill", label:"발열·오한 묻기"});
MERGE (:ChecklistItem {id:"ask_urinary_symptoms", label:"배뇨증상(배뇨통·빈뇨·혈뇨) 묻기"});
MERGE (:ChecklistItem {id:"ask_pregnancy_menstruation", label:"임신·월경력 묻기"});
MERGE (:ChecklistItem {id:"exam_cva_tenderness", label:"갈비척추각압통 진찰"});
MERGE (:Test {id:"urinalysis", label:"요검사"});
MERGE (:Test {id:"pregnancy_test_hcg", label:"소변 임신검사(hCG)"});
MERGE (:Test {id:"blood_test", label:"혈액검사"});
MERGE (:Test {id:"kub_xray", label:"단순 X선(KUB)"});
MERGE (:Test {id:"stone_ct", label:"비조영 CT(요로결석)"});
MERGE (:DiseaseDifferential {id:"pyelonephritis", label:"급성 신우신염"});
MERGE (:Symptom {id:"dysuria_frequency", label:"배뇨통·빈뇨"});
MERGE (:RedFlag {id:"sepsis_sign", label:"패혈증 징후"});
MERGE (:Test {id:"urine_culture", label:"소변배양검사"});
MERGE (:DiseaseDifferential {id:"ectopic_pregnancy", label:"자궁외임신"});
MERGE (:Symptom {id:"lower_abdominal_pain", label:"하복부 통증"});
MERGE (:Symptom {id:"amenorrhea", label:"무월경"});
MERGE (:Symptom {id:"vaginal_bleeding", label:"질출혈"});
MERGE (:Symptom {id:"dizziness_syncope", label:"어지럼/실신"});
MERGE (:Symptom {id:"pregnancy_possible", label:"임신 가능성"});
MERGE (:RedFlag {id:"hypotension_shock", label:"저혈압/쇼크"});
MERGE (:RedFlag {id:"syncope", label:"실신"});
MERGE (:ChecklistItem {id:"ask_menstrual_history", label:"월경력 묻기"});
MERGE (:ChecklistItem {id:"ask_sexual_contraception", label:"성생활·피임력 묻기"});
MERGE (:ChecklistItem {id:"ask_vaginal_bleeding", label:"질출혈 묻기"});
MERGE (:ChecklistItem {id:"exclude_pregnancy", label:"임신 배제(검사)"});
MERGE (:Test {id:"beta_hcg", label:"임신검사(β-hCG)"});
MERGE (:Test {id:"transvaginal_us", label:"경질 초음파"});
MERGE (:DiseaseDifferential {id:"pelvic_inflammatory_disease", label:"골반염(PID)"});
MERGE (:Symptom {id:"vaginal_discharge", label:"질분비물"});
MERGE (:Symptom {id:"cervical_motion_tenderness", label:"자궁경부 운동통"});
MERGE (:Symptom {id:"sexual_activity_history", label:"성접촉력"});
MERGE (:Symptom {id:"deep_dyspareunia", label:"깊은 성교통"});
MERGE (:RedFlag {id:"tubo_ovarian_abscess", label:"난관난소 농양"});
MERGE (:ChecklistItem {id:"ask_vaginal_discharge", label:"질분비물 묻기"});
MERGE (:ChecklistItem {id:"ask_sexual_history", label:"성생활력 묻기"});
MERGE (:ChecklistItem {id:"exam_pelvic", label:"골반 진찰"});
MERGE (:Test {id:"pelvic_exam_test", label:"내진"});
MERGE (:Test {id:"sti_test", label:"성매개감염 검사"});
MATCH (a {id:"abdominal_pain"}), (b {id:"acute_appendicitis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"rlq_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"pain_migration_periumbilical_to_rlq"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"fever_low_grade"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"anorexia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"nausea_vomiting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"rebound_tenderness"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"peritoneal_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"high_fever"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"ask_onset_duration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"ask_location_migration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"ask_associated_fever_gi"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"exam_rebound_tenderness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"abdominal_ct"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"acute_appendicitis"}), (b {id:"cbc"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"peptic_ulcer_disease"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"epigastric_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"relation_to_meals"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"heartburn"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"nocturnal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"relieved_by_antacid"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"melena"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"postprandial_vomiting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"gi_bleeding"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"perforation_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"gastric_cancer_ddx"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"ask_meal_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"ask_heartburn"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"ask_nsaid_history"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"ask_alarm_features"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"peptic_ulcer_disease"}), (b {id:"egd"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"acute_cholecystitis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"ruq_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"worse_after_fatty_meal"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"radiation_to_right_shoulder"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"murphy_sign"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"fever_chill"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"jaundice"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"charcot_triad"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"high_fever"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"ask_pain_location_radiation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"ask_fever_jaundice"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"exam_murphy_sign"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"abdominal_ultrasound"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"acute_cholecystitis"}), (b {id:"lft"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"acute_pancreatitis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"epigastric_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"radiation_to_back"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"worse_lying_better_leaning_forward"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"persistent_severe_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"nausea_vomiting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"alcohol_or_gallstone_history"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"shock_organ_failure"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"high_fever"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"ask_pain_location_radiation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"ask_alcohol_history"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"ask_nausea_vomiting"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"ask_prior_gallstone"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"serum_lipase_amylase"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"acute_pancreatitis"}), (b {id:"abdominal_ct"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"gastroenteritis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"diffuse_crampy_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"nausea_vomiting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"recent_food_or_contact"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"mild_self_limiting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"dehydration_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"bloody_stool"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"ask_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"ask_food_history"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"ask_sick_contacts"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"ask_dehydration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"gastroenteritis"}), (b {id:"stool_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"bowel_obstruction"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"crampy_abdominal_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"abdominal_distension"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"vomiting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"obstipation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"hyperactive_then_absent_bowel_sounds"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"peritoneal_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"strangulation_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"ask_bowel_gas_passage"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"ask_prior_surgery"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"ask_vomiting"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"exam_abdominal_distension"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"abdominal_xray"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"bowel_obstruction"}), (b {id:"abdominal_ct"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"diverticulitis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"llq_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"fever"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"altered_bowel_habit"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"localized_tenderness"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"peritoneal_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"perforation_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"ask_pain_location"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"ask_bowel_habit_change"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"ask_fever"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"exam_llq_tenderness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"diverticulitis"}), (b {id:"abdominal_ct"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"ureteral_stone"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"flank_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"sudden_severe_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"cva_tenderness"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"position_independent_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"hematuria"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"radiation_to_groin"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"obstruction_pyelonephritis"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"acute_kidney_injury"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"ask_onset_duration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"ask_pain_location_radiation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"ask_character"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"ask_fever_chill"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"ask_urinary_symptoms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"ask_pregnancy_menstruation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"exam_cva_tenderness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"urinalysis"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"pregnancy_test_hcg"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"kub_xray"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ureteral_stone"}), (b {id:"stone_ct"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"pyelonephritis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"flank_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"fever_chill"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"cva_tenderness"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"dysuria_frequency"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"nausea_vomiting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"sepsis_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"ask_fever_chill"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"ask_urinary_symptoms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"ask_pain_location"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"exam_cva_tenderness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"urinalysis"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"pyelonephritis"}), (b {id:"urine_culture"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"ectopic_pregnancy"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"lower_abdominal_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"amenorrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"vaginal_bleeding"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"dizziness_syncope"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"pregnancy_possible"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"hypotension_shock"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"syncope"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"ask_menstrual_history"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"ask_sexual_contraception"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"ask_vaginal_bleeding"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"exclude_pregnancy"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"beta_hcg"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ectopic_pregnancy"}), (b {id:"transvaginal_us"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"abdominal_pain"}), (b {id:"pelvic_inflammatory_disease"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"lower_abdominal_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"vaginal_discharge"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"cervical_motion_tenderness"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"fever"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"sexual_activity_history"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"deep_dyspareunia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"tubo_ovarian_abscess"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"peritoneal_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"ask_vaginal_discharge"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"ask_sexual_history"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"ask_fever"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"exam_pelvic"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"beta_hcg"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"pelvic_exam_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"pelvic_inflammatory_disease"}), (b {id:"sti_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
