// 흉통 온톨로지 — YAML→Cypher 자동생성. 정본=ontology/chest_pain.yaml. 손편집 금지.
MATCH (n) DETACH DELETE n;
MERGE (:ChiefComplaint {id:"chest_pain", label:"흉통"});
MERGE (:DiseasePrimary {id:"acute_coronary_syndrome", label:"급성 관상동맥증후군(ACS)"});
MERGE (:Symptom {id:"chest_pressure", label:"쥐어짜는 압박감"});
MERGE (:Symptom {id:"exertional_or_rest_onset", label:"운동/안정 시 발생"});
MERGE (:Symptom {id:"radiation_to_left_arm_or_jaw", label:"좌측 팔·턱 방사"});
MERGE (:Symptom {id:"diaphoresis", label:"식은땀"});
MERGE (:Symptom {id:"dyspnea", label:"호흡곤란"});
MERGE (:RedFlag {id:"hypotension", label:"저혈압"});
MERGE (:RedFlag {id:"syncope", label:"실신"});
MERGE (:ChecklistItem {id:"ask_onset_duration", label:"발병·기간 묻기"});
MERGE (:ChecklistItem {id:"ask_character", label:"통증 양상 묻기"});
MERGE (:ChecklistItem {id:"ask_radiation", label:"방사 묻기"});
MERGE (:ChecklistItem {id:"ask_aggravating_relieving", label:"악화·완화인자 묻기"});
MERGE (:ChecklistItem {id:"ask_associated_sx", label:"동반증상 묻기"});
MERGE (:ChecklistItem {id:"ask_cardiac_risk_factors", label:"심혈관 위험인자 묻기"});
MERGE (:Test {id:"ecg_12lead", label:"12유도 심전도"});
MERGE (:Test {id:"cardiac_troponin", label:"심근 트로포닌"});
MERGE (:DiseaseDifferential {id:"aortic_dissection", label:"대동맥박리"});
MERGE (:Symptom {id:"sudden_tearing_pain", label:"갑작스런 찢어지는 통증"});
MERGE (:Symptom {id:"maximal_at_onset", label:"시작 시 최고조"});
MERGE (:Symptom {id:"radiation_to_back", label:"등으로 방사"});
MERGE (:Symptom {id:"bp_differential_between_arms", label:"양팔 혈압차"});
MERGE (:Symptom {id:"hypertension_hx", label:"고혈압 병력"});
MERGE (:RedFlag {id:"bp_differential", label:"양팔 혈압차"});
MERGE (:RedFlag {id:"neurologic_deficit", label:"신경학적 결손"});
MERGE (:ChecklistItem {id:"ask_onset_abruptness", label:"발병 급격성 묻기"});
MERGE (:ChecklistItem {id:"ask_tearing_quality", label:"찢어지는 양상 묻기"});
MERGE (:ChecklistItem {id:"ask_radiation_to_back", label:"등 방사 묻기"});
MERGE (:ChecklistItem {id:"measure_bp_both_arms", label:"양팔 혈압 측정"});
MERGE (:Test {id:"ct_angiography", label:"CT 혈관조영"});
MERGE (:DiseaseDifferential {id:"pulmonary_embolism", label:"폐색전증"});
MERGE (:Symptom {id:"pleuritic_chest_pain", label:"흡기성 흉통(숨쉴 때 악화)"});
MERGE (:Symptom {id:"tachycardia", label:"빈맥"});
MERGE (:Symptom {id:"immobilization_or_dvt_risk", label:"부동·수술·DVT 위험"});
MERGE (:Symptom {id:"hemoptysis", label:"객혈"});
MERGE (:RedFlag {id:"hypoxia_shock", label:"저산소·쇼크(대량 색전)"});
MERGE (:ChecklistItem {id:"ask_dyspnea", label:"호흡곤란 묻기"});
MERGE (:ChecklistItem {id:"ask_dvt_risk", label:"부동·수술·장거리이동 묻기"});
MERGE (:ChecklistItem {id:"ask_leg_swelling", label:"다리 부종 묻기"});
MERGE (:Test {id:"ct_pulmonary_angiography", label:"CT 폐동맥조영"});
MERGE (:Test {id:"d_dimer", label:"D-dimer"});
MERGE (:DiseaseDifferential {id:"pneumothorax", label:"기흉"});
MERGE (:Symptom {id:"sudden_pleuritic_chest_pain", label:"갑작스런 흡기성 흉통"});
MERGE (:Symptom {id:"decreased_breath_sounds", label:"환측 호흡음 감소"});
MERGE (:Symptom {id:"worse_with_deep_breath", label:"심호흡 시 악화"});
MERGE (:Symptom {id:"tall_thin_or_copd_history", label:"마른 체형/폐질환(결핵·폐기종) 과거력"});
MERGE (:RedFlag {id:"tension_pneumothorax", label:"긴장성 기흉(응급)"});
MERGE (:ChecklistItem {id:"ask_lung_disease_history", label:"폐질환 과거력 묻기"});
MERGE (:ChecklistItem {id:"exam_breath_sounds", label:"호흡음 청진"});
MERGE (:Test {id:"chest_xray", label:"흉부 X선"});
MERGE (:DiseaseDifferential {id:"pericarditis", label:"심막염"});
MERGE (:Symptom {id:"positional_pain_worse_supine", label:"누우면 악화·앉으면 완화"});
MERGE (:Symptom {id:"sharp_pain", label:"날카로운 통증"});
MERGE (:Symptom {id:"recent_viral_illness", label:"최근 바이러스 감염력"});
MERGE (:Symptom {id:"pericardial_friction_rub", label:"심막마찰음"});
MERGE (:RedFlag {id:"pericardial_effusion_tamponade", label:"심막삼출·심장눌림증(응급)"});
MERGE (:ChecklistItem {id:"ask_positional_pleuritic", label:"자세·호흡 연관 묻기"});
MERGE (:ChecklistItem {id:"ask_recent_infection", label:"최근 감염력 묻기"});
MERGE (:ChecklistItem {id:"exam_auscultation_rub", label:"심막마찰음 청진"});
MERGE (:DiseaseDifferential {id:"gerd", label:"위식도역류질환(GERD)"});
MERGE (:Symptom {id:"retrosternal_burning", label:"흉골 뒤 작열감"});
MERGE (:Symptom {id:"relation_to_meals_or_lying_down", label:"식후/눕기와 연관"});
MERGE (:Symptom {id:"acid_regurgitation", label:"산 역류"});
MERGE (:Symptom {id:"relieved_by_antacid", label:"제산제로 완화"});
MERGE (:Symptom {id:"no_exertional_relation", label:"운동과 무관"});
MERGE (:RedFlag {id:"dysphagia", label:"연하곤란"});
MERGE (:RedFlag {id:"weight_loss", label:"체중감소"});
MERGE (:RedFlag {id:"gi_bleeding", label:"위장관 출혈"});
MERGE (:ChecklistItem {id:"ask_relation_to_meals", label:"식사 연관 묻기"});
MERGE (:ChecklistItem {id:"ask_regurgitation", label:"역류 묻기"});
MERGE (:ChecklistItem {id:"ask_antacid_response", label:"제산제 반응 묻기"});
MERGE (:ChecklistItem {id:"ask_alarm_features", label:"경고증상 묻기"});
MERGE (:DiseaseDifferential {id:"musculoskeletal_chest_pain", label:"근골격계 흉통"});
MERGE (:Symptom {id:"localized_pain", label:"국소 통증"});
MERGE (:Symptom {id:"reproducible_on_movement", label:"움직임으로 재현"});
MERGE (:Symptom {id:"pain_on_chest_wall_palpation", label:"흉벽 압통"});
MERGE (:Symptom {id:"worse_with_breathing_or_motion", label:"호흡/동작 시 악화"});
MERGE (:Symptom {id:"strain_history", label:"무리·외상 과거력"});
MERGE (:ChecklistItem {id:"ask_palpation_reproducibility", label:"압통 재현 확인"});
MERGE (:ChecklistItem {id:"ask_movement_relation", label:"동작 연관 묻기"});
MERGE (:ChecklistItem {id:"ask_trauma_hx", label:"외상력 묻기"});
MERGE (:ChecklistItem {id:"exam_chest_wall", label:"흉벽 진찰"});
MERGE (:DiseaseDifferential {id:"panic_anxiety", label:"공황/불안"});
MERGE (:Symptom {id:"chest_tightness", label:"가슴 답답함"});
MERGE (:Symptom {id:"palpitations", label:"두근거림"});
MERGE (:Symptom {id:"hyperventilation", label:"과호흡"});
MERGE (:Symptom {id:"paresthesia", label:"손발 저림"});
MERGE (:Symptom {id:"situational_trigger", label:"상황 유발"});
MERGE (:Symptom {id:"young_low_risk", label:"젊고 위험인자 적음"});
MERGE (:RedFlag {id:"must_exclude_cardiac_first", label:"심장 원인 우선 배제"});
MERGE (:ChecklistItem {id:"ask_anxiety_sx", label:"불안증상 묻기"});
MERGE (:ChecklistItem {id:"ask_triggers", label:"유발요인 묻기"});
MERGE (:ChecklistItem {id:"ask_pattern", label:"발작 양상 묻기"});
MERGE (:ChecklistItem {id:"exclude_red_flags", label:"red flag 배제"});
MATCH (a {id:"chest_pain"}), (b {id:"acute_coronary_syndrome"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"chest_pressure"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"exertional_or_rest_onset"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"radiation_to_left_arm_or_jaw"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"diaphoresis"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"dyspnea"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"hypotension"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"syncope"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"ask_onset_duration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"ask_character"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"ask_radiation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"ask_aggravating_relieving"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"ask_associated_sx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"ask_cardiac_risk_factors"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"ecg_12lead"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"acute_coronary_syndrome"}), (b {id:"cardiac_troponin"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"chest_pain"}), (b {id:"aortic_dissection"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"sudden_tearing_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"maximal_at_onset"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"radiation_to_back"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"bp_differential_between_arms"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"hypertension_hx"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"bp_differential"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"neurologic_deficit"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"syncope"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"hypotension"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"ask_onset_abruptness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"ask_tearing_quality"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"ask_radiation_to_back"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"measure_bp_both_arms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"aortic_dissection"}), (b {id:"ct_angiography"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"chest_pain"}), (b {id:"pulmonary_embolism"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"pleuritic_chest_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"dyspnea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"tachycardia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"immobilization_or_dvt_risk"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"hemoptysis"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"hypoxia_shock"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"ask_dyspnea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"ask_dvt_risk"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"ask_leg_swelling"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"ct_pulmonary_angiography"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"pulmonary_embolism"}), (b {id:"d_dimer"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"chest_pain"}), (b {id:"pneumothorax"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"sudden_pleuritic_chest_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"dyspnea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"decreased_breath_sounds"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"worse_with_deep_breath"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"tall_thin_or_copd_history"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"tension_pneumothorax"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"ask_dyspnea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"ask_lung_disease_history"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"exam_breath_sounds"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pneumothorax"}), (b {id:"chest_xray"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"chest_pain"}), (b {id:"pericarditis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"pleuritic_chest_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"positional_pain_worse_supine"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"sharp_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"recent_viral_illness"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"pericardial_friction_rub"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"pericardial_effusion_tamponade"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"ask_positional_pleuritic"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"ask_recent_infection"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"exam_auscultation_rub"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"pericarditis"}), (b {id:"ecg_12lead"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"chest_pain"}), (b {id:"gerd"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"gerd"}), (b {id:"retrosternal_burning"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"gerd"}), (b {id:"relation_to_meals_or_lying_down"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"gerd"}), (b {id:"acid_regurgitation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"gerd"}), (b {id:"relieved_by_antacid"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"gerd"}), (b {id:"no_exertional_relation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"gerd"}), (b {id:"dysphagia"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"gerd"}), (b {id:"weight_loss"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"gerd"}), (b {id:"gi_bleeding"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"gerd"}), (b {id:"ask_relation_to_meals"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"gerd"}), (b {id:"ask_regurgitation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"gerd"}), (b {id:"ask_antacid_response"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"gerd"}), (b {id:"ask_alarm_features"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"chest_pain"}), (b {id:"musculoskeletal_chest_pain"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"localized_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"reproducible_on_movement"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"pain_on_chest_wall_palpation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"worse_with_breathing_or_motion"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"strain_history"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"ask_palpation_reproducibility"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"ask_movement_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"ask_trauma_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"musculoskeletal_chest_pain"}), (b {id:"exam_chest_wall"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"chest_pain"}), (b {id:"panic_anxiety"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"chest_tightness"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"palpitations"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"hyperventilation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"paresthesia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"situational_trigger"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"young_low_risk"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"must_exclude_cardiac_first"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"ask_anxiety_sx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"ask_triggers"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"ask_pattern"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"panic_anxiety"}), (b {id:"exclude_red_flags"}) MERGE (a)-[:CHECKLIST]->(b);
