// 변비 온톨로지 — YAML→Cypher 자동생성. 정본=ontology/constipation.yaml. 손편집 금지.
MATCH (n) DETACH DELETE n;
MERGE (:ChiefComplaint {id:"constipation", label:"변비"});
MERGE (:DiseasePrimary {id:"functional_constipation", label:"기능성 변비"});
MERGE (:Symptom {id:"infrequent_bowel_movement", label:"배변 횟수 감소(주 3회 미만)"});
MERGE (:Symptom {id:"hard_lumpy_stool", label:"딱딱하고 덩어리진 변"});
MERGE (:Symptom {id:"abdominal_discomfort", label:"복부 불편감"});
MERGE (:Symptom {id:"low_fiber_low_fluid_intake", label:"섬유질·수분 섭취 부족"});
MERGE (:Symptom {id:"sedentary_lifestyle", label:"좌식 생활·운동 부족"});
MERGE (:Symptom {id:"no_alarm_feature", label:"경고징후 없음"});
MERGE (:Symptom {id:"normal_rectal_exam", label:"직장수지검사 정상"});
MERGE (:RedFlag {id:"fecal_impaction", label:"분변 매복"});
MERGE (:RedFlag {id:"constipation_alarm_features", label:"변비 경보증상(발열·식욕부진·구토·혈변·빈혈·체중감소·대장암 가족력·50세 이후 시작)"});
MERGE (:ChecklistItem {id:"ask_onset_duration_constipation", label:"언제부터 변비였는지 묻기"});
MERGE (:ChecklistItem {id:"ask_bowel_frequency", label:"배변 횟수·간격 묻기"});
MERGE (:ChecklistItem {id:"ask_stool_hardness", label:"변이 딱딱한지 묻기"});
MERGE (:ChecklistItem {id:"ask_blood_in_stool", label:"변에 피가 섞이는지 묻기"});
MERGE (:ChecklistItem {id:"ask_stool_caliber_change", label:"변 굵기 변화 묻기"});
MERGE (:ChecklistItem {id:"ask_incomplete_evacuation", label:"잔변감 묻기"});
MERGE (:ChecklistItem {id:"ask_abdominal_pain", label:"복통·복부불편 묻기"});
MERGE (:ChecklistItem {id:"ask_diet_exercise_habit", label:"식사·운동 습관 묻기"});
MERGE (:ChecklistItem {id:"ask_smoking_alcohol", label:"흡연·음주 묻기"});
MERGE (:ChecklistItem {id:"ask_family_hx_crc", label:"대장암 가족력 묻기"});
MERGE (:ChecklistItem {id:"exam_abdomen_auscultation", label:"복부 청진"});
MERGE (:ChecklistItem {id:"exam_abdomen_percussion", label:"복부 타진"});
MERGE (:ChecklistItem {id:"exam_abdomen_palpation", label:"복부 촉진"});
MERGE (:ChecklistItem {id:"exam_digital_rectal", label:"직장수지검사"});
MERGE (:ChecklistItem {id:"exam_stool_color_on_glove", label:"장갑 손가락의 대변 색 확인"});
MERGE (:Test {id:"cbc_blood_test", label:"일반혈액검사"});
MERGE (:Test {id:"thyroid_function_test", label:"갑상선 검사"});
MERGE (:Test {id:"colonic_transit_study", label:"대변통과시간검사"});
MERGE (:Test {id:"colonoscopy", label:"대장내시경"});
MERGE (:DiseaseDifferential {id:"rectocele", label:"직장류"});
MERGE (:Symptom {id:"incomplete_evacuation", label:"잔변감"});
MERGE (:Symptom {id:"excessive_straining", label:"과도한 힘주기"});
MERGE (:Symptom {id:"vaginal_pressure_to_defecate", label:"질 뒤벽을 눌러야 배변"});
MERGE (:Symptom {id:"digital_maneuver_to_evacuate", label:"손가락으로 변을 빼내야 함"});
MERGE (:Symptom {id:"prolonged_defecation_time", label:"배변 시간 연장"});
MERGE (:Symptom {id:"female_with_obstetric_hx", label:"여성·분만력"});
MERGE (:ChecklistItem {id:"ask_stool_form", label:"변의 형태 묻기"});
MERGE (:ChecklistItem {id:"ask_defecation_time", label:"배변 시간 묻기"});
MERGE (:ChecklistItem {id:"ask_straining", label:"힘을 많이 주는지 묻기"});
MERGE (:ChecklistItem {id:"ask_digital_or_enema_use", label:"관장·손가락 사용 여부 묻기"});
MERGE (:ChecklistItem {id:"ask_easy_difficult_situations", label:"배변 난이도가 달라지는 상황 묻기"});
MERGE (:ChecklistItem {id:"ask_weight_change", label:"체중 변화 묻기"});
MERGE (:ChecklistItem {id:"ask_prior_colonoscopy", label:"대장내시경 시행력 묻기"});
MERGE (:ChecklistItem {id:"ask_past_illness", label:"과거 질환 치료력 묻기"});
MERGE (:ChecklistItem {id:"exam_position_for_rectal", label:"직장진찰 자세 취하게 하기"});
MERGE (:ChecklistItem {id:"exam_perianal_inspection", label:"항문 주변 시진·촉진"});
MERGE (:Test {id:"defecography", label:"배변조영술"});
MERGE (:Test {id:"anorectal_manometry", label:"항문직장내압검사"});
MERGE (:DiseaseDifferential {id:"rectal_prolapse", label:"직장탈출증"});
MERGE (:Symptom {id:"protruding_anal_mass", label:"배변 시 항문 밖으로 나오는 덩이"});
MERGE (:Symptom {id:"mucus_discharge", label:"점액 분비"});
MERGE (:Symptom {id:"fecal_soiling", label:"변 지림"});
MERGE (:RedFlag {id:"incarcerated_prolapse", label:"감돈된 탈출(응급)"});
MERGE (:ChecklistItem {id:"exam_strain_simulated_evacuation", label:"힘주기 시 회음 하강·치골직장근 확인"});
MERGE (:DiseaseDifferential {id:"dyssynergic_defecation", label:"배변협조장애(골반저기능장애)"});
MERGE (:Symptom {id:"paradoxical_puborectalis_contraction", label:"힘줄 때 치골직장근 역설수축"});
MERGE (:Symptom {id:"failure_of_perineal_descent", label:"회음부 하강 부족"});
MERGE (:Symptom {id:"need_perineal_support", label:"회음부를 받쳐야 배변"});
MERGE (:Symptom {id:"high_anal_sphincter_tone", label:"항문괄약근 긴장도 증가"});
MERGE (:Test {id:"balloon_expulsion_test", label:"풍선배출검사"});
MERGE (:DiseaseDifferential {id:"ibs_constipation", label:"과민성대장증후군(변비형)"});
MERGE (:Symptom {id:"recurrent_abdominal_pain", label:"반복되는 복통"});
MERGE (:Symptom {id:"altered_stool_frequency_or_form", label:"배변 횟수·변 형태 변화"});
MERGE (:Symptom {id:"pain_relieved_by_defecation", label:"배변 후 복통 완화"});
MERGE (:Symptom {id:"alternating_diarrhea", label:"설사와 교대"});
MERGE (:Symptom {id:"bloating", label:"복부 팽만"});
MERGE (:Symptom {id:"no_weight_loss", label:"체중감소 없음"});
MERGE (:DiseaseDifferential {id:"colorectal_cancer_constipation", label:"대장암"});
MERGE (:Symptom {id:"recent_onset_constipation", label:"최근에 새로 생긴 변비"});
MERGE (:Symptom {id:"change_in_stool_caliber", label:"변 굵기 변화"});
MERGE (:Symptom {id:"hematochezia", label:"혈변"});
MERGE (:Symptom {id:"weight_loss", label:"체중감소"});
MERGE (:Symptom {id:"anemia_symptoms", label:"빈혈 증상(피로·창백)"});
MERGE (:Symptom {id:"age_over_50", label:"50세 이상"});
MERGE (:Symptom {id:"family_hx_colorectal_cancer", label:"대장암 가족력"});
MERGE (:RedFlag {id:"alarm_weight_loss", label:"경고징후 — 체중감소"});
MERGE (:RedFlag {id:"alarm_rectal_bleeding", label:"경고징후 — 직장 출혈"});
MERGE (:RedFlag {id:"alarm_anemia", label:"경고징후 — 빈혈"});
MERGE (:RedFlag {id:"bowel_obstruction_sign", label:"장폐색 징후"});
MERGE (:RedFlag {id:"palpable_mass_with_habit_change", label:"배변습관 변화 + 촉지되는 종괴"});
MERGE (:Test {id:"abdominal_xray", label:"복부 X선"});
MERGE (:DiseaseDifferential {id:"drug_induced_constipation", label:"약물유발 변비"});
MERGE (:Symptom {id:"temporal_relation_to_drug", label:"약물 시작과 시간적 연관"});
MERGE (:Symptom {id:"opioid_or_anticholinergic_use", label:"아편유사제·항콜린제 복용"});
MERGE (:Symptom {id:"calcium_blocker_or_antidepressant", label:"칼슘차단제·항우울제 복용"});
MERGE (:ChecklistItem {id:"ask_medication_hx", label:"복용 약물력 묻기"});
MERGE (:DiseaseDifferential {id:"hypothyroidism_constipation", label:"갑상선기능저하증"});
MERGE (:Symptom {id:"cold_intolerance", label:"추위를 못 참음"});
MERGE (:Symptom {id:"fatigue_weight_gain", label:"피로·체중증가"});
MERGE (:Symptom {id:"dry_skin_bradycardia", label:"피부건조·서맥"});
MERGE (:ChecklistItem {id:"ask_hypothyroid_symptoms", label:"갑상선기능저하 증상 묻기"});
MERGE (:DiseaseDifferential {id:"hypercalcemia_constipation", label:"고칼슘혈증"});
MERGE (:Symptom {id:"polyuria_polydipsia", label:"다뇨·다음"});
MERGE (:Symptom {id:"hypercalcemia", label:"고칼슘혈증"});
MERGE (:Symptom {id:"muscle_weakness_confusion", label:"근력저하·의식혼탁"});
MERGE (:ChecklistItem {id:"ask_neurologic_symptoms", label:"신경학적 증상·과거력 묻기"});
MERGE (:Test {id:"serum_calcium_potassium", label:"혈청 칼슘·칼륨"});
MERGE (:DiseaseDifferential {id:"electrolyte_disturbance", label:"전해질 이상(저칼륨혈증 등)"});
MERGE (:Symptom {id:"hypokalemia", label:"저칼륨혈증"});
MERGE (:RedFlag {id:"megacolon", label:"거대결장"});
MERGE (:DiseaseDifferential {id:"slow_transit_constipation", label:"서행성 변비"});
MERGE (:Symptom {id:"no_urge_to_defecate", label:"변의 자체가 드묾"});
MERGE (:Symptom {id:"prolonged_colonic_transit", label:"대장통과시간 지연"});
MERGE (:Symptom {id:"laxative_dependence", label:"완하제 의존"});
MERGE (:DiseaseDifferential {id:"anal_fissure", label:"치열(anal fissure)"});
MERGE (:Symptom {id:"painful_defecation", label:"배변 시·후 항문 통증"});
MERGE (:Symptom {id:"sharp_sudden_anal_pain", label:"날카롭고 갑작스러운 항문 통증(부종 없음)"});
MERGE (:Symptom {id:"bright_red_blood_on_tissue", label:"휴지에 묻는 선홍색 피"});
MERGE (:Symptom {id:"stool_withholding_due_to_pain", label:"통증 때문에 변을 참음"});
MERGE (:RedFlag {id:"atypical_fissure_secondary", label:"비전형 치열(직장염·크론병 등 이차성 원인)"});
MERGE (:Test {id:"anoscopy_perianal_exam", label:"항문경·항문주위 진찰"});
MERGE (:DiseaseDifferential {id:"internal_hemorrhoid", label:"내치핵(internal hemorrhoid)"});
MERGE (:Symptom {id:"painless_bright_red_bleeding", label:"무통성 선홍색 출혈"});
MERGE (:Symptom {id:"hemorrhoid_prolapse", label:"배변 시 치핵 탈출"});
MERGE (:DiseaseDifferential {id:"neurogenic_constipation", label:"신경질환성 변비"});
MERGE (:Symptom {id:"parkinsonism_or_neurologic_disease", label:"파킨슨병·신경질환"});
MERGE (:Symptom {id:"spinal_cord_injury_hx", label:"척수손상 과거력"});
MERGE (:Symptom {id:"diabetic_autonomic_neuropathy", label:"당뇨병성 자율신경병증"});
MERGE (:RedFlag {id:"cauda_equina_syndrome", label:"마미증후군(요폐·안장부 감각저하·회음부 저림) — 즉시 영상·수술 평가"});
MERGE (:RedFlag {id:"loss_of_anal_reflex", label:"항문반사 소실(S2–S4 반사궁 병변)"});
MATCH (a {id:"constipation"}), (b {id:"functional_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"infrequent_bowel_movement"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"hard_lumpy_stool"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"abdominal_discomfort"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"low_fiber_low_fluid_intake"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"sedentary_lifestyle"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"no_alarm_feature"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"normal_rectal_exam"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"fecal_impaction"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"constipation_alarm_features"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_onset_duration_constipation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_bowel_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_stool_hardness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_blood_in_stool"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_stool_caliber_change"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_incomplete_evacuation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_abdominal_pain"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_diet_exercise_habit"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_smoking_alcohol"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"ask_family_hx_crc"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"exam_abdomen_auscultation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"exam_abdomen_percussion"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"exam_stool_color_on_glove"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"thyroid_function_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"colonic_transit_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"functional_constipation"}), (b {id:"colonoscopy"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"rectocele"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"rectocele"}), (b {id:"incomplete_evacuation"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"rectocele"}), (b {id:"excessive_straining"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"rectocele"}), (b {id:"vaginal_pressure_to_defecate"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectocele"}), (b {id:"digital_maneuver_to_evacuate"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectocele"}), (b {id:"prolonged_defecation_time"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectocele"}), (b {id:"female_with_obstetric_hx"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_bowel_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_stool_form"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_defecation_time"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_straining"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_incomplete_evacuation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_digital_or_enema_use"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_easy_difficult_situations"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_blood_in_stool"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_weight_change"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_prior_colonoscopy"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_diet_exercise_habit"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_past_illness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"ask_family_hx_crc"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"exam_abdomen_auscultation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"exam_abdomen_percussion"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"exam_position_for_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"exam_perianal_inspection"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"defecography"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"rectocele"}), (b {id:"anorectal_manometry"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"rectal_prolapse"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"protruding_anal_mass"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"incomplete_evacuation"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"mucus_discharge"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"fecal_soiling"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"excessive_straining"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"female_with_obstetric_hx"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"incarcerated_prolapse"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"ask_straining"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"ask_incomplete_evacuation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"ask_digital_or_enema_use"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"ask_blood_in_stool"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"exam_perianal_inspection"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"exam_strain_simulated_evacuation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"defecography"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"rectal_prolapse"}), (b {id:"anorectal_manometry"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"dyssynergic_defecation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"excessive_straining"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"incomplete_evacuation"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"paradoxical_puborectalis_contraction"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"failure_of_perineal_descent"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"need_perineal_support"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"high_anal_sphincter_tone"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"fecal_impaction"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"ask_straining"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"ask_defecation_time"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"ask_incomplete_evacuation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"ask_digital_or_enema_use"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"exam_strain_simulated_evacuation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"anorectal_manometry"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"balloon_expulsion_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"dyssynergic_defecation"}), (b {id:"defecography"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"ibs_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"recurrent_abdominal_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"altered_stool_frequency_or_form"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"pain_relieved_by_defecation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"alternating_diarrhea"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"bloating"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"no_weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"ask_onset_duration_constipation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"ask_bowel_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"ask_stool_form"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"ask_abdominal_pain"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"ask_incomplete_evacuation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"ask_diet_exercise_habit"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ibs_constipation"}), (b {id:"colonoscopy"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"colorectal_cancer_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"recent_onset_constipation"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"change_in_stool_caliber"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"hematochezia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"anemia_symptoms"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"age_over_50"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"family_hx_colorectal_cancer"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"alarm_weight_loss"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"alarm_rectal_bleeding"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"alarm_anemia"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"bowel_obstruction_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"palpable_mass_with_habit_change"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"ask_onset_duration_constipation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"ask_stool_caliber_change"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"ask_blood_in_stool"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"ask_weight_change"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"ask_prior_colonoscopy"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"ask_family_hx_crc"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"exam_stool_color_on_glove"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"colonoscopy"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"colorectal_cancer_constipation"}), (b {id:"abdominal_xray"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"drug_induced_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"infrequent_bowel_movement"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"temporal_relation_to_drug"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"opioid_or_anticholinergic_use"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"calcium_blocker_or_antidepressant"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"hard_lumpy_stool"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"fecal_impaction"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"ask_onset_duration_constipation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"ask_bowel_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"ask_past_illness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_constipation"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"hypothyroidism_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"infrequent_bowel_movement"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"cold_intolerance"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"fatigue_weight_gain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"dry_skin_bradycardia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"hard_lumpy_stool"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"ask_hypothyroid_symptoms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"ask_weight_change"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"ask_past_illness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"thyroid_function_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"hypothyroidism_constipation"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"hypercalcemia_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"polyuria_polydipsia"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"hypercalcemia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"muscle_weakness_confusion"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"infrequent_bowel_movement"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"ask_past_illness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"ask_weight_change"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"ask_neurologic_symptoms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"serum_calcium_potassium"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"hypercalcemia_constipation"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"electrolyte_disturbance"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"infrequent_bowel_movement"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"hypokalemia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"muscle_weakness_confusion"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"megacolon"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"ask_past_illness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"ask_neurologic_symptoms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"serum_calcium_potassium"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"electrolyte_disturbance"}), (b {id:"thyroid_function_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"slow_transit_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"infrequent_bowel_movement"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"no_urge_to_defecate"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"prolonged_colonic_transit"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"laxative_dependence"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"hard_lumpy_stool"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"bloating"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"megacolon"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"fecal_impaction"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"ask_bowel_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"ask_onset_duration_constipation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"ask_digital_or_enema_use"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"exam_abdomen_percussion"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"colonic_transit_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"abdominal_xray"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"slow_transit_constipation"}), (b {id:"anorectal_manometry"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"anal_fissure"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"painful_defecation"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"sharp_sudden_anal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"bright_red_blood_on_tissue"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"stool_withholding_due_to_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"high_anal_sphincter_tone"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"alarm_rectal_bleeding"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"atypical_fissure_secondary"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"ask_blood_in_stool"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"ask_stool_hardness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"ask_straining"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"exam_perianal_inspection"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"anal_fissure"}), (b {id:"anoscopy_perianal_exam"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"internal_hemorrhoid"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"painless_bright_red_bleeding"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"hemorrhoid_prolapse"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"bright_red_blood_on_tissue"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"excessive_straining"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"alarm_rectal_bleeding"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"ask_blood_in_stool"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"ask_straining"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"exam_perianal_inspection"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"internal_hemorrhoid"}), (b {id:"anoscopy_perianal_exam"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"constipation"}), (b {id:"neurogenic_constipation"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"infrequent_bowel_movement"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"parkinsonism_or_neurologic_disease"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"spinal_cord_injury_hx"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"diabetic_autonomic_neuropathy"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"no_urge_to_defecate"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"sedentary_lifestyle"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"megacolon"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"fecal_impaction"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"cauda_equina_syndrome"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"loss_of_anal_reflex"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"ask_neurologic_symptoms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"ask_past_illness"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"ask_bowel_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"colonic_transit_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"anorectal_manometry"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"neurogenic_constipation"}), (b {id:"abdominal_xray"}) MERGE (a)-[:INDICATED_TEST]->(b);
