// 설사 온톨로지 — YAML→Cypher 자동생성. 정본=ontology/diarrhea.yaml. 손편집 금지.
MATCH (n) DETACH DELETE n;
MERGE (:ChiefComplaint {id:"diarrhea", label:"설사"});
MERGE (:DiseasePrimary {id:"ibs_diarrhea", label:"과민성대장증후군(설사형)"});
MERGE (:Symptom {id:"chronic_recurrent_diarrhea", label:"만성·재발성 설사(4주 초과)"});
MERGE (:Symptom {id:"abdominal_pain_with_diarrhea", label:"설사 동반 복통"});
MERGE (:Symptom {id:"pain_relieved_by_defecation", label:"배변 후 복통 완화"});
MERGE (:Symptom {id:"no_nocturnal_symptoms", label:"야간에는 증상 없음"});
MERGE (:Symptom {id:"stress_related_symptoms", label:"스트레스와 연관"});
MERGE (:Symptom {id:"alternating_constipation", label:"변비와 교대"});
MERGE (:Symptom {id:"no_weight_loss", label:"체중감소 없음"});
MERGE (:ChecklistItem {id:"ask_onset_duration_diarrhea", label:"언제부터 설사했는지 묻기"});
MERGE (:ChecklistItem {id:"ask_stool_frequency", label:"설사 빈도 묻기"});
MERGE (:ChecklistItem {id:"ask_stool_form", label:"변의 형태 묻기"});
MERGE (:ChecklistItem {id:"ask_stool_volume", label:"변의 양 묻기"});
MERGE (:ChecklistItem {id:"ask_pain_with_diarrhea", label:"설사 시 복통 묻기"});
MERGE (:ChecklistItem {id:"ask_pain_onset", label:"복통 시작 시기 묻기"});
MERGE (:ChecklistItem {id:"ask_pain_relief", label:"복통 호전 상황 묻기"});
MERGE (:ChecklistItem {id:"ask_stress_relation", label:"스트레스 연관 묻기"});
MERGE (:ChecklistItem {id:"exam_abdomen_auscultation", label:"복부 청진"});
MERGE (:ChecklistItem {id:"exam_abdomen_percussion", label:"복부 타진"});
MERGE (:ChecklistItem {id:"exam_abdomen_palpation", label:"복부 촉진"});
MERGE (:ChecklistItem {id:"exam_digital_rectal", label:"항문·직장 진찰"});
MERGE (:Test {id:"cbc_blood_test", label:"혈액검사"});
MERGE (:Test {id:"stool_study", label:"대변검사"});
MERGE (:Test {id:"colonoscopy", label:"결장경(대장내시경)"});
MERGE (:DiseaseDifferential {id:"viral_gastroenteritis", label:"바이러스 장염"});
MERGE (:Symptom {id:"acute_watery_diarrhea", label:"급성 물설사"});
MERGE (:Symptom {id:"vomiting_prominent", label:"구토 우세"});
MERGE (:Symptom {id:"fever_present", label:"발열"});
MERGE (:Symptom {id:"outbreak_contact", label:"집단발생·주변 동일증상"});
MERGE (:Symptom {id:"crampy_abdominal_pain", label:"경련성 복통"});
MERGE (:RedFlag {id:"dehydration_signs", label:"탈수 징후(구강건조·갈증)"});
MERGE (:RedFlag {id:"elderly_or_immunocompromised", label:"고령(≥70세)·면역저하"});
MERGE (:ChecklistItem {id:"ask_fever_chills", label:"발열·오한 묻기"});
MERGE (:ChecklistItem {id:"ask_thirst_dehydration", label:"갈증·탈수 묻기"});
MERGE (:ChecklistItem {id:"exam_dehydration_tongue", label:"탈수 평가(혀·구강)"});
MERGE (:Test {id:"serum_electrolytes", label:"혈청 전해질"});
MERGE (:DiseaseDifferential {id:"invasive_bacterial_enterocolitis", label:"침습성 세균성 장염(Campylobacter·Salmonella·Yersinia)"});
MERGE (:Symptom {id:"inflammatory_diarrhea", label:"염증성(침습성) 설사 — 혈변·발열 동반"});
MERGE (:Symptom {id:"high_fever", label:"고열"});
MERGE (:Symptom {id:"severe_abdominal_pain", label:"심한 복통"});
MERGE (:Symptom {id:"fecal_leukocytes", label:"대변 백혈구"});
MERGE (:RedFlag {id:"fever_over_38_5", label:"발열 ≥38.5℃"});
MERGE (:RedFlag {id:"toxic_megacolon", label:"독성 거대결장"});
MERGE (:ChecklistItem {id:"ask_blood_or_color", label:"변 색깔·혈변 묻기"});
MERGE (:ChecklistItem {id:"ask_food_relation", label:"음식과 증상 연관성 묻기"});
MERGE (:Test {id:"stool_culture_pcr", label:"대변 배양·분자검사"});
MERGE (:DiseaseDifferential {id:"shigellosis_dysentery", label:"세균성 이질(Shigella)"});
MERGE (:Symptom {id:"bloody_diarrhea", label:"혈성 설사(이질)"});
MERGE (:Symptom {id:"tenesmus_mucoid_stool", label:"뒤무직·점액변"});
MERGE (:RedFlag {id:"overtly_bloody_stool", label:"육안적 혈변"});
MERGE (:RedFlag {id:"hemolytic_uremic_syndrome", label:"용혈요독증후군(HUS)"});
MERGE (:DiseaseDifferential {id:"stec_infection", label:"장출혈성 대장균(STEC·O157:H7) 감염"});
MERGE (:Symptom {id:"initially_nonbloody_then_bloody", label:"처음엔 비혈성이다가 혈성으로 변함"});
MERGE (:Symptom {id:"undercooked_beef_unpasteurized_milk", label:"덜 익힌 소고기·저온살균 안 한 우유"});
MERGE (:Symptom {id:"minimal_or_no_fever", label:"발열 없거나 미미"});
MERGE (:RedFlag {id:"stec_antibiotic_contraindication", label:"STEC 의심 시 항생제·지사제 금기"});
MERGE (:DiseaseDifferential {id:"preformed_toxin_food_poisoning", label:"전구성 독소 식중독(황색포도알균·B. cereus 구토독소)"});
MERGE (:Symptom {id:"onset_within_hours_of_meal", label:"식후 수 시간(1~6h) 내 발생"});
MERGE (:Symptom {id:"shared_meal_history", label:"같은 음식 먹은 사람 동시 발병"});
MERGE (:DiseaseDifferential {id:"in_vivo_toxin_food_poisoning", label:"정착 후 독소생성 식중독(C. perfringens 등)"});
MERGE (:Symptom {id:"onset_6_24h_after_meal", label:"식후 6~24시간 발생"});
MERGE (:Symptom {id:"reheated_food_history", label:"다시 데우거나 오래 방치한 음식 섭취"});
MERGE (:DiseaseDifferential {id:"travelers_diarrhea", label:"여행자 설사"});
MERGE (:Symptom {id:"recent_travel_history", label:"최근 여행·타지역 방문력"});
MERGE (:Symptom {id:"watery_diarrhea_during_travel", label:"여행 중·직후 물설사"});
MERGE (:ChecklistItem {id:"ask_recent_travel", label:"최근 여행·타지역 방문 묻기"});
MERGE (:DiseaseDifferential {id:"cdi_antibiotic_associated", label:"항생제연관 설사(C. difficile)"});
MERGE (:Symptom {id:"recent_antibiotic_use", label:"최근 항생제 사용력"});
MERGE (:Symptom {id:"healthcare_exposure", label:"입원·요양시설 노출"});
MERGE (:ChecklistItem {id:"ask_antibiotic_hx", label:"최근 항생제 사용 묻기"});
MERGE (:ChecklistItem {id:"ask_medication_hx", label:"복용 약물력 묻기"});
MERGE (:Test {id:"cdiff_toxin_assay", label:"C. difficile 독소검사"});
MERGE (:DiseaseDifferential {id:"inflammatory_bowel_disease", label:"염증성 장질환(크론·궤양성대장염)"});
MERGE (:Symptom {id:"chronic_bloody_diarrhea", label:"만성 혈성 설사"});
MERGE (:Symptom {id:"weight_loss", label:"체중감소"});
MERGE (:Symptom {id:"extraintestinal_manifestation", label:"장외 증상(관절·눈·피부)"});
MERGE (:Symptom {id:"young_adult_onset", label:"젊은 나이 발병"});
MERGE (:RedFlag {id:"bowel_obstruction_sign", label:"장폐색 징후"});
MERGE (:ChecklistItem {id:"ask_weight_loss", label:"체중감소 묻기"});
MERGE (:ChecklistItem {id:"ask_family_hx", label:"가족력 묻기"});
MERGE (:Test {id:"fecal_calprotectin", label:"대변 칼프로텍틴"});
MERGE (:DiseaseDifferential {id:"lactose_intolerance", label:"유당불내증(삼투성)"});
MERGE (:Symptom {id:"symptoms_after_dairy", label:"유제품 섭취 후 증상"});
MERGE (:Symptom {id:"bloating_flatus", label:"복부팽만·가스"});
MERGE (:Symptom {id:"resolves_with_fasting", label:"금식하면 호전"});
MERGE (:ChecklistItem {id:"ask_dairy_relation", label:"유제품 섭취 연관 묻기"});
MERGE (:Test {id:"lactose_breath_test", label:"유당 호기검사"});
MERGE (:DiseaseDifferential {id:"hyperthyroidism_diarrhea", label:"갑상선기능항진증"});
MERGE (:Symptom {id:"heat_intolerance", label:"더위를 못 참음"});
MERGE (:Symptom {id:"palpitations", label:"두근거림"});
MERGE (:Symptom {id:"unintentional_weight_loss", label:"의도치 않은 체중감소"});
MERGE (:Symptom {id:"goiter_or_thyroid_disease_hx", label:"갑상선 종대·질환 과거력"});
MERGE (:ChecklistItem {id:"ask_hyperthyroid_symptoms", label:"갑상선기능항진 증상 묻기"});
MERGE (:ChecklistItem {id:"exam_thyroid", label:"갑상샘 진찰"});
MERGE (:Test {id:"thyroid_function_test", label:"갑상선기능검사"});
MERGE (:DiseaseDifferential {id:"bile_acid_diarrhea", label:"담즙산 설사(담낭절제·회장질환 후)"});
MERGE (:Symptom {id:"cholecystectomy_or_ileal_surgery_hx", label:"담낭절제·회장 수술 과거력"});
MERGE (:Symptom {id:"urgency_after_meals", label:"식후 급박변"});
MERGE (:ChecklistItem {id:"ask_abdominal_surgery_hx", label:"복부수술(담낭절제) 과거력 묻기"});
MERGE (:DiseaseDifferential {id:"colorectal_cancer_diarrhea", label:"대장암"});
MERGE (:Symptom {id:"hematochezia", label:"혈변"});
MERGE (:Symptom {id:"change_in_stool_caliber", label:"변 굵기 변화"});
MERGE (:Symptom {id:"age_over_50", label:"50세 이상"});
MERGE (:Symptom {id:"family_hx_colorectal_cancer", label:"대장암 가족력"});
MERGE (:Symptom {id:"anemia_symptoms", label:"빈혈 증상(피로·창백)"});
MERGE (:RedFlag {id:"severe_pain_over_age_50", label:"50세 초과에서 심한 복통"});
MERGE (:DiseaseDifferential {id:"drug_induced_diarrhea", label:"약물유발 설사"});
MERGE (:Symptom {id:"temporal_relation_to_drug", label:"약물 시작과 시간적 연관"});
MERGE (:Symptom {id:"laxative_or_antidiarrheal_use", label:"완하제·지사제 복용력"});
MATCH (a {id:"diarrhea"}), (b {id:"ibs_diarrhea"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"chronic_recurrent_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"abdominal_pain_with_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"pain_relieved_by_defecation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"no_nocturnal_symptoms"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"stress_related_symptoms"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"alternating_constipation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"no_weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_stool_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_stool_form"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_stool_volume"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_pain_with_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_pain_onset"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_pain_relief"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"ask_stress_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"exam_abdomen_auscultation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"exam_abdomen_percussion"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"ibs_diarrhea"}), (b {id:"colonoscopy"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"viral_gastroenteritis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"acute_watery_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"vomiting_prominent"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"fever_present"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"outbreak_contact"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"crampy_abdominal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"dehydration_signs"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"elderly_or_immunocompromised"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"ask_stool_frequency"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"ask_thirst_dehydration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"exam_dehydration_tongue"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"viral_gastroenteritis"}), (b {id:"serum_electrolytes"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"invasive_bacterial_enterocolitis"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"inflammatory_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"high_fever"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"severe_abdominal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"fecal_leukocytes"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"fever_over_38_5"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"toxic_megacolon"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"ask_blood_or_color"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"stool_culture_pcr"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"invasive_bacterial_enterocolitis"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"shigellosis_dysentery"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"inflammatory_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"bloody_diarrhea"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"high_fever"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"tenesmus_mucoid_stool"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"severe_abdominal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"fecal_leukocytes"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"overtly_bloody_stool"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"fever_over_38_5"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"hemolytic_uremic_syndrome"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"ask_blood_or_color"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"stool_culture_pcr"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"shigellosis_dysentery"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"stec_infection"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"initially_nonbloody_then_bloody"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"severe_abdominal_pain"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"undercooked_beef_unpasteurized_milk"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"minimal_or_no_fever"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"hemolytic_uremic_syndrome"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"stec_antibiotic_contraindication"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"overtly_bloody_stool"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"ask_blood_or_color"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"ask_thirst_dehydration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"stool_culture_pcr"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"stec_infection"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"preformed_toxin_food_poisoning"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"acute_watery_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"onset_within_hours_of_meal"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"vomiting_prominent"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"minimal_or_no_fever"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"shared_meal_history"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"dehydration_signs"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"ask_thirst_dehydration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"exam_dehydration_tongue"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"preformed_toxin_food_poisoning"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"in_vivo_toxin_food_poisoning"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"acute_watery_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"onset_6_24h_after_meal"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"reheated_food_history"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"crampy_abdominal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"minimal_or_no_fever"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"shared_meal_history"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"dehydration_signs"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"ask_thirst_dehydration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"exam_dehydration_tongue"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"in_vivo_toxin_food_poisoning"}), (b {id:"stool_culture_pcr"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"travelers_diarrhea"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"acute_watery_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"recent_travel_history"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"watery_diarrhea_during_travel"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"crampy_abdominal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"minimal_or_no_fever"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"dehydration_signs"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"overtly_bloody_stool"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"ask_recent_travel"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"ask_thirst_dehydration"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"exam_dehydration_tongue"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"travelers_diarrhea"}), (b {id:"stool_culture_pcr"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"cdi_antibiotic_associated"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"acute_watery_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"recent_antibiotic_use"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"crampy_abdominal_pain"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"healthcare_exposure"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"fever_present"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"toxic_megacolon"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"fever_over_38_5"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"elderly_or_immunocompromised"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"ask_antibiotic_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"cdiff_toxin_assay"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"cdi_antibiotic_associated"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"inflammatory_bowel_disease"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"chronic_recurrent_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"chronic_bloody_diarrhea"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"abdominal_pain_with_diarrhea"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"extraintestinal_manifestation"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"young_adult_onset"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"overtly_bloody_stool"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"toxic_megacolon"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"bowel_obstruction_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"ask_blood_or_color"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"ask_weight_loss"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"ask_fever_chills"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"ask_family_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"colonoscopy"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"fecal_calprotectin"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"inflammatory_bowel_disease"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"lactose_intolerance"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"chronic_recurrent_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"symptoms_after_dairy"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"bloating_flatus"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"resolves_with_fasting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"no_weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"ask_dairy_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"ask_stool_form"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"ask_pain_with_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"lactose_intolerance"}), (b {id:"lactose_breath_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"hyperthyroidism_diarrhea"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"chronic_recurrent_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"heat_intolerance"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"palpitations"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"unintentional_weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"goiter_or_thyroid_disease_hx"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"ask_hyperthyroid_symptoms"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"ask_weight_loss"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"ask_family_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"exam_thyroid"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"thyroid_function_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"hyperthyroidism_diarrhea"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"bile_acid_diarrhea"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"chronic_recurrent_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"cholecystectomy_or_ileal_surgery_hx"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"urgency_after_meals"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"no_weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"ask_abdominal_surgery_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"ask_stool_form"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"ask_food_relation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"bile_acid_diarrhea"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"colorectal_cancer_diarrhea"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"chronic_recurrent_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"hematochezia"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"change_in_stool_caliber"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"age_over_50"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"family_hx_colorectal_cancer"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"anemia_symptoms"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"overtly_bloody_stool"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"bowel_obstruction_sign"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"severe_pain_over_age_50"}) MERGE (a)-[:HAS_RED_FLAG]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"ask_blood_or_color"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"ask_weight_loss"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"ask_family_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"ask_stool_form"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"exam_abdomen_palpation"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"exam_digital_rectal"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"colonoscopy"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"colorectal_cancer_diarrhea"}), (b {id:"stool_study"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"diarrhea"}), (b {id:"drug_induced_diarrhea"}) MERGE (a)-[:PRESENTS_AS]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"chronic_recurrent_diarrhea"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"temporal_relation_to_drug"}) MERGE (a)-[:REQUIRES_SYMPTOM]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"laxative_or_antidiarrheal_use"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"resolves_with_fasting"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"no_weight_loss"}) MERGE (a)-[:DISCRIMINATOR]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"ask_medication_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"ask_antibiotic_hx"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"ask_onset_duration_diarrhea"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"ask_stool_form"}) MERGE (a)-[:CHECKLIST]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"cbc_blood_test"}) MERGE (a)-[:INDICATED_TEST]->(b);
MATCH (a {id:"drug_induced_diarrhea"}), (b {id:"serum_electrolytes"}) MERGE (a)-[:INDICATED_TEST]->(b);
